baseurl = "/"
title = "Leonardo Hansa"
author = "Leonardo Hansa"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

summaryLength = 70

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "Programo porque es resultón"
  dateform = "02/01/2006"
  title = "Cosa"
  
[[permalinks]]
    title = "Cosa"
    post = "/:year/:month/:day/:slug/"

  
[[menu.main]]
    name = "Newsletter"
    url = "/post/"
    description = "Ejemplos de cosas que te envío al correo"
    weight = 1
[[menu.main]]
    name = "Mediocre"
    url = "/soy-mediocre/"
    description = "Sobre mí"
    weight = 2

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
    
[sitemap]
  changefreq = 'never'
  filename = 'sitemap.xml'
  priority = 0.5