baseurl = "/"
title = "Leonardo Hansa"
author = "Leonardo Hansa"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "Programo porque es resultón"
  dateform = "02/01/2006"
  title = "Cosa"
  
[[permalinks]]
    title = "Cosa"
    post = "/:year/:month/:day/:slug/"

  
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/lhansa"
    weight = 1
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/leonardohansa"
    weight = 2
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/l_hansa"
    weight = 3
[[menu.main]]
    name = "Cursos"
    url = "https://lhansa.github.io/"
    weight = 4
